### ISSUE TITLE
Dane dla grafu połączeń

### ISSUE THREAD

**Issue by anrog** [Antyradek/auskylia#10]
Algorytm ewolucyjny generalnie działa, chciałbym teraz wiedzieć, jakie dane mają być przez model generowane, a jakie ma wziąć z zewnątrz.

Poza rzeczami oczywistymi jak liczba wierzchołków, wielkość populacji, czy współczynniki przy kryteriach oceny ścieżki, potrzebuję także macierzy z parametrami krawędzi - cena, czas, bezpieczeństwo etc.
Poza tym muszę wiedzieć, do jakich przedziałów mogą te wielkości należeć, czy są całkowite czy rzeczywiste i czy zależą jakoś od siebie.

Proszę zatem wybrać opcję:
1. Model dostaje samą liczbę wierzchołków i generuje cały graf (tak, jak obecnie).
2. Model dostaje listę kolejnych wierzchołków (np. nazwy miast) i generuje graf.
3. Model dostaje współrzędne wierzchołków (typ? przedział?) w przestrzeni dwuwymiarowej (płaszczyzna/sfera?), na ich podstawie generuje graf.
4. Model dostaje macierz krawędzi i tylko liczy.

Z tego co zrozumiałem z plików z komendami, celujemy w opcję 2. lub 3.
Pełna lista lotnisk żadnych współrzędnych nie ma - to by mi wskazywało na opcję 2. chyba, że jeszcze się one tam pojawią.

**Comment by sigrond** [comment]
Tak, celujemy raczej w opcję 2, szczególnie, że ustaliliśmy już, że projekt nie musi mieć prawie nic wspólnego z rzeczywistością.
Jeśli chodzi o listę lotnisk, to z mojej strony nie ma raczej szans na dodanie tam współrzędnych, gdyż lista ta powstała przez prostą, automatyczną zamianę formatu danych listy znalezionej w internecie.

**Comment by anrog** [comment]
Doskonale, mi to pasuje, bo nic nie będę musiał zmieniać w modelu, tylko zamapować lotniska na liczby.

Inicjalizacja kontenerem ze stringami, jednym wielkim stringiem w formacie jak w pliku z komendami czy nazwą pliku z listą lotnisk?

**Comment by sigrond** [comment]
Wydaje mi się, że najmniej byłoby komplikacji, jeśli sam byś wczytał plik z listą lotnisk. Jeśli nie masz ochoty pisać od początku, to możesz użyć mojego kodu z /controller/Controller.cpp i /controller/XMLParser.cpp. Niestety nie mam jak do tej pory kodu parsującego listę lotnisk. Dobrze by było, gdybyś ogarnął co się dzieje w /model/Model.cpp i zrobiłbyś żeby przy poleceniu obliczeń i zapytania o status robiło się to co powinno, bo ja nie ogarniam jak używać tego co napisałeś.

**Comment by Antyradek** [comment]
Ściągnąłem i przeparsowałem plik lotnisk, są dostępne w katalogu airport_parser. 
Są to wszystkie potrzebne dane do działania, łącznie z pozycjami geograficznymi, odległościami, sztucznie wyliczonymi danymi. Dane są plikiem oddzielonym spacjami, więc można go wciągnąć prosto do strumienia. Nazwy mają zamienione spacje na _.
W razie czego można zmienić algorytm i przegenerować jeszcze raz.
Więcej info w readme.

Nie trzeba wysyłać współrzędnych do widoku, i tak ich nie wyświetlimy żadna przeglądarka nie wytrzyma mapy z kilkoma tysiącami markerów.
