### ISSUE TITLE
Zapytania ajax/jquery get do serwera

### ISSUE THREAD

**Issue by sigrond** [Antyradek/auskylia#3]
Jak rozumiem śliczna :heart:  strona z commitu a0b8fea729176fadeaa58fe0f4c64a964d702ea0 nie wysyła jeszcze zapytań do serwera. Jeśli zaczeła by wysyłać jakieś proste zapytania po kliknięciu guźika, to mógłbym dość łatwo napisać w serwerze widoku #2 odbieranie tych zapytań.

**Comment by Antyradek** [comment]
Wysyła. Jest tylko problem, gdyż przeglądarka nie widzi tych plików jako serwer i nie pozwala wykonywać POST na plikach lokalnych ze względów bezpieczeństwa.
