### ISSUE TITLE
xmlhttprequest for local files

### ISSUE THREAD

**Issue by sigrond** [Antyradek/auskylia#4]
Wybierz proszę jedno z zaproponowanych rozwiązań i zastosuj.
http://stackoverflow.com/questions/7683596/xmlhttprequest-for-local-files

**Comment by Antyradek** [comment]
Wybrałem dopisanie do nagłówka Cross-Origin.
To jest niebezpieczny sposób i wymaga, aby użytkownik posiadał pliki html do odpalenia oraz wpisał do klienta adres serwera (albo localhost) i port. Strona nie jest ściągana z serwera.

**Comment by sigrond** [comment]
Sądzę, że problemy komunikacji kontrolera z widokiem zostały już w większości rozwiązane i dodatkowo serwer zwraca plik ze stroną.
Zamykam temat.
