### ISSUE TITLE
Propozycja zmiany sposobu krzyżowania i mutacji ścieżek.

### ISSUE THREAD

**Issue by anrog** [Antyradek/auskylia#6]
Obecnie krzyżowanie ścieżek przyjmuje podejście klasyczne: mianowicie dla każdego genu (węzła grafu) nowej ścieżki, losowo jest wybierany rodzic, po którym gen zostanie odziedziczony.
Prowadzi to od tego, że dwie sensowne ścieżki generują dwa z dupy wzięte zygzaki.

Moja propozycja jest taka, by krzyżowanie robić na zasadzie wyjęcia z każdej ścieżki-rodzica jednej losowej krawędzi i "pozszywanie" uzyskanych części między sobą.
Pic related: https://my.mixtape.moe/pvjkdh.png

Dajcie znać, co o tym myślicie. Z punktu widzenia implementacji, będzie to znacznie lepsze niż obecny horror.

**Comment by sigrond** [comment]
Tak. Myślę, że taki sposób krzyżowania ma dużo sensu, szczególnie jeśli przyspieszy i ułatwi to implementację. Taki sposób krzyżowania wydaje się być bardziej zbliżony do naturalnego. Jednak należy zwrócić uwagę, że możemy w ten sposób znacznie zmniejszyć możliwość uzyskania pewnych ścieżek. Należało by dopilnować, żeby mutacje występowały często, w dużej ilości i niektóre powinny być znaczne.

Można by też zamiast tego przyznawać każdemu wierzchołkowi pewną liczbę mówiąca na której pozycji powinien się znaleźć z najwyższym prawdopodobieństwem i następnie powstawiać (uszeregować) losowo wierzchołki, każdy z rozkładem prawdopodobieństwa. Czyli wierzchołek posiada pewną zmienną float pozycja według której wierzchołki są uszeregowane (posortowane) i przy krzyżowaniu wartość ta dla każdego wierzchołka jest losowana jeszcze raz, tak, że stara wartość jest najbardziej prawdopodobna, czyli np. jest to szczyt rozkładu naturalnego.

**Comment by anrog** [comment]
Nowe krzyżowanie działa dobrze, zamykam.
