### ISSUE TITLE
Problemy z długą listą lotnisk w widoku

### ISSUE THREAD

**Issue by sigrond** [Antyradek/auskylia#9]
W commicie 3cde36319a5bc17ad70f842b3f89500343bfd37c dodałem listę chyba wszystkich lotnisk na świecie. Pierwszą rzeczą, która rzuciła mi się w oczy, to długi czas wczytywania tej listy przez JavaScript widoku. Zamiast zupełnego zamarznięcia karty przeglądarki wolałbym tą ładną klepsydrę z komunikatem: "Wczytywanie listy lotnisk...".
Następny problem, który zauważyłem, to trudność znalezienia właściwego miasta na liście. Da się wybrać tylko pierwszą literę, a miast na tą samą literę jest bardzo dużo. HTML5 i JavaScript zapewniają ładne i wygodne mechanizmy wyszukiwania słów na liście. Myślę, że wygodne pole wyszukiwania miasta jest niezbędne.
Można by tutaj też wykorzystać dodatkowo google maps api do umożliwienia użytkownikowi wybrania lotniska na mapie.

**Comment by Antyradek** [comment]
Podziękujmy twórcom JS, że jest jednowątkowa i parsowanie danych wstrzymuje animacje JQuery. Teraz działa i nawet wykrywa błędy. (Nie zaglądajcie w kod, bo wypali wam oczy).

**Comment by Antyradek** [comment]
Filtrowanie listy po wpisywanym tekście jest trudne i czasochłonne do implementacji. I tak nie dostaniemy za to punktów.
